from selenium.webdriver.common.by import By
from typing import Tuple


ENTER_AND_REGISTRATION_BUTTON: tuple[str, str] = (By.XPATH, './/button[contains(text(), "Вход и регистрация")]')
NO_ACCOUNT_BUTTON: tuple[str, str] = (By.XPATH, './/button[contains(text(), "Нет аккаунта")]')
EMAIL_INPUT: tuple[str, str] = (By.XPATH, ".//input[@placeholder='Введите Email']")
PASSWORD_INPUT: tuple[str, str] = (By.NAME, "password")
REPEAT_PASSWORD_INPUT: tuple[str, str] = (By.NAME, "submitPassword")
CREATE_ACCOUNT_BUTTON: tuple[str, str] = (By.XPATH, './/button[contains(text(), "Создать аккаунт")]')
ACCOUNT_PHOTO: tuple[str, str] = (By.CSS_SELECTOR, "svg.svgSmall")
ACCOUNT_NAME: tuple[str, str] = (By.XPATH, './/h3[contains(text(), "User.")]')
HIGHLIGHT_RED_ERRORS: tuple[str, str] = (By.CLASS_NAME, "input_inputError__fLUP9")
ERROR: tuple[str, str] = (By.XPATH, './/span[contains(text(), "Ошибка")]')
ENTER_BUTTON: tuple[str, str] = (By.XPATH, ".//button[contains(text(), 'Войти')]")
EXIT_BUTTON: tuple[str, str] = (By.XPATH, ".//button[contains(text(), 'Выйти')]")
CREATE_ANNOUNCEMENT_BUTTON: tuple[str, str] = (By.XPATH, ".//button[contains(text(), 'Разместить объявление')]")
MODAL_WINDOW: tuple[str, str] = (By.XPATH, ".//form[@class = 'popUp_shell__LuyqR']")
TITLE: tuple[str, str] = (By.XPATH, ".//input[@placeholder='Название']")
DESCRIPTION: tuple[str, str] = (By.XPATH, ".//textarea[@placeholder='Описание товара']")
PRICE: tuple[str, str] = (By.XPATH, ".//input[@placeholder='Стоимость']")
CATEGORY_DROPDOWN: tuple[str, str] = (By.XPATH, ".//input[@name='category']/parent::div/button")
CATEGORY: tuple[str, str] = (By.XPATH, ".//span[contains(text(), 'Авто')]/parent::button")
CITY_DROPDOWN: tuple[str, str] = (By.XPATH, ".//input[@name='city']/parent::div/button")
CITY: tuple[str, str] = (By.XPATH, ".//span[contains(text(), 'Санкт-Петербург')]/parent::button")
CONDITION: tuple[str, str] = (By.XPATH, ".//input[@value='Б/У']/parent::div/div")
PUBLISH_BUTTON: tuple[str, str] = (By.XPATH, './/button[contains(text(), "Опубликовать")]')
PROFILE_BUTTON: tuple[str, str] = (By.XPATH, './/button[@class = "circleSmall"]')
ANNOUNCEMENT_IN_PROFILE: tuple[str, str] = (By.XPATH, './/div[@class = "card"]')
